services:
  - type: web
    name: text-to-sql-ai-chatbot
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: NVIDIA_API_KEY
        sync: false # User will input this securely on Render dashboard
